#!/bin/dash
#
# This script is a verbatim copy of:
#
# * https://askubuntu.com/a/875855
# * https://ubuntuforums.org/showthread.php?t=1739495
#
# It's copied into this repository to make it easier to find and easier to run.
#
# See also:
#
# * https://www.gnu.org/software/grub/manual/grub/grub.html#play
# * https://gitlab.com/lukasfink1/midi2grub
# * https://askubuntu.com/questions/76309/play-a-sound-before-or-after-grub-loads
# * https://forums.linuxmint.com/viewtopic.php?t=174854

if [ $# -lt 3 ]; then
    echo "Usage: $0 tempo freq dur [freq dur freq dur...]" >&2
    exit 1
fi

tempo=$1; shift

tmpdir=$(mktemp -d)

while [ -n "$*" ]; do
    freq=$1; shift
    dur=$1;  shift
    dur=$(echo "$dur*(60/$tempo)"|bc -l)
    sox -e mu-law -r 8000 -n -t raw - synth $dur sine $freq >>$tmpdir/grubtune.ul 2> /dev/null
done

play -q -c1 -r 8000 $tmpdir/grubtune.ul

rm -r $tmpdir
