#!/usr/bin/expect -f

# This script uses expect(1) to interact with a password prompt.

# It calls "foobar --foo baz"...
spawn foobar --foo baz

# Then it expects receiving a "Password:" prompt.
expect "Password:" {
# Alternatively, it can also support regex:
# expect -re {Password for [^:]*:} {

	# Then it sends a password that is unsafely stored as plaintext right here:
	send -- "correct.horse.battery.staple\r"
}

# Finally, it expects to receive a prompt for a 2FA TOTP token.
expect -re "(Two Factor|2FA) Token:" {
	# Here, the user can type the token.
	interact
}

wait

# An additional newline can be printed to stdout, if needed.
send_user -- "\r"
